# Generated by Django 4.1.4 on 2023-04-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.TextField()),
                ('type', models.TextField()),
                ('max_players', models.IntegerField()),
                ('min_players', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('phone', models.TextField()),
                ('profile_pic', models.ImageField(upload_to=None)),
                ('is_organizer', models.BooleanField()),
                ('is_player', models.BooleanField()),
                ('prefered_position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('evaluated_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_evaluations', to='soccer.user')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_evaluated', to='soccer.user')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_evaluated', to='soccer.user')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_evaluations', to='soccer.matches')),
                ('player_scores', models.ManyToManyField(related_name='match_evaluations_player_scores', to='soccer.playerevaluation')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_organized', to='soccer.user'),
        ),
        migrations.AddField(
            model_name='matches',
            name='players',
            field=models.ManyToManyField(related_name='matches_played', to='soccer.user'),
        ),
    ]
